version: '3.8'
services:
  public-site:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    image: explizit-public-site:deploy
    container_name: explizit-public-site-deploy
    ports:
      - "8080:80"
    restart: unless-stopped
